name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  selenium-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Selenium Tests
        run: mvn clean test